name: Docker

on:
  push:
  pull_request:

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Push, remove and run image
        run: |
          IMAGE_PATH=docker.pkg.github.com/${{ github.repository }}/image:latest

          # Build and tag image
          docker build . --file Dockerfile --tag $IMAGE_PATH --build-arg MESSAGE=${{ github.sha }}

          # Publish image
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
          docker push $IMAGE_PATH
          
          # Pull image
          docker pull $IMAGE_PATH
          
          # Run image
          docker run $IMAGE_PATH
